namespace: dev

replicaCount: 1

image:
  repository: bitnami/rabbitmq
  tag: 4.1.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  amqpPort: 5672
  managementPort: 15672
  headlessName: rabbitmq-headless

rabbitmq:
  defaultUser: admin
  defaultPass: admin
  defaultVhost: /
  config:
    mnesiaBase: /bitnami/rabbitmq/mnesia  # Aligné avec le StatefulSet
    additionalErlArgs: "+sbwt none +sbwtdcpu none +sbwtdio none +stbt db"
    ctlErlArgs: "+P 1048576 +K true +A 128"

persistence:
  size: 1Gi
  storageClass: local-path
  mountPath: /bitnami/rabbitmq/mnesia  # Aligné avec le StatefulSet

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  exec:
    command:
      - rabbitmq-diagnostics
      - -q
      - ping
  initialDelaySeconds: 60
  timeoutSeconds: 30
  periodSeconds: 20
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  exec:
    command:
      - rabbitmq-diagnostics
      - -q
      - ping
  initialDelaySeconds: 60
  timeoutSeconds: 30
  periodSeconds: 20
  successThreshold: 1
  failureThreshold: 6
  