apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headlessName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672