apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headlessName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - port: {{ .Values.service.amqpPort }}
      name: amqp
    - port: {{ .Values.service.managementPort }}
      name: management
