apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.defaultUser }}
  password: {{ .Values.rabbitmq.defaultPass }}
