apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.amqpPort }}
      name: amqp
    - port: {{ .Values.service.managementPort }}
      name: management
  selector:
    app: rabbitmq
