apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: 5672
      nodePort: {{ .Values.service.amqpNodePort }}
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: 15672
      nodePort: {{ .Values.service.managementNodePort }}
