apiVersion: v1
kind: Service
metadata:
  name: catalogdb-headless
  namespace: dev
spec:
  clusterIP: None
  selector:
    app: catalogdb
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432