apiVersion: v1
kind: Secret
metadata:
  name: catalogdb-secrets
  namespace: dev
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # "postgres" en base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # "password" en base64