apiVersion: v1
kind: Service
metadata:
  name: catalogdb
  namespace: dev
spec:
  selector:
    app: catalogdb
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30433
  type: NodePort