apiVersion: v1
kind: Secret
metadata:
  name: catalogdb-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | b64enc | quote }}
