apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalogdb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: catalogdb
  serviceName: catalogdb
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: catalogdb-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalogdb-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB | quote }}
            - name: PGDATA
              value: {{ .Values.env.PGDATA | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: init-db-script
              mountPath: /docker-entrypoint-initdb.d/init-db.sh
              subPath: init-db.sh
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: {{ toJson .Values.livenessProbe.exec.command }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
      volumes:
        - name: init-db-script
          configMap:
            name: catalogdb-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: {{ .Values.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
