image:
  repository: redis
  tag: 7.2-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

redis:
  password: "redis"
  config:
    bind: "0.0.0.0"
    maxmemory: "256mb"
    maxmemoryPolicy: "allkeys-lru"

healthcheck:
  command: ["redis-cli", "ping"]
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

persistence:
  enabled: true
  size: 1Gi
  storageClass: local-path
  mountPath: /data
